name: Metrics
on:
  # 🌏 Think about the planet! No need to update stats too frequently
  schedule: [{ cron: "0 0 * * *" }]
  # 💡 The following line lets you run workflow manually from the action tab!
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🦑 Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_KEY }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_fortune: yes

      - name: 🦑 General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_KEY }}
          base: header
          base-indepth: yes
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: lua, GLSL, C, Jupyter Notebook, HTML, CSS, SCSS, Emacs Lisp, Renderscript
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 5
          
      - name: LeetCode
        uses: lowlighter/metrics@latest
        with:
          filename: leetcode.svg
          token: NOT_NEEDED
          base: ""
          plugin_leetcode_user: hegde_atri
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent


      - name: Licenses
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: licenses.svg
          token: ${{ secrets.METRICS_KEY }}
          base: ""
          plugin_licenses: yes
          plugin_licenses_setup: bash -c '[[ -f package.json ]] && npm ci || true
          plugin_licenses_legal: no
          plugin_licenses_ratio: yes
